ALTER TABLE users
ADD COLUMN firstname VARCHAR(20) DEFAULT 'john',
ADD COLUMN lastname VARCHAR(20) DEFAULT 'doe',
ADD COLUMN degree VARCHAR(20) DEFAULT '.',
ADD COLUMN training_year INTEGER DEFAULT 0
